# Generated by Django 2.1.1 on 2018-10-04 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20181004_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='theme',
            field=models.CharField(max_length=20, null=True, verbose_name='博客主题'),
        ),
    ]
